### ISSUE TITLE
opsweekly on Kubernetes/Helm

### ISSUE THREAD

**Issue by yahavb** [ninoabbate/docker-opsweekly#2]
We are using opsweekly deployed thru Kubernetes and Helm. I took most of the docker specs from this repo. Want me to fork the repo and add the k8s and helm support? I have it working in GKE and AWS.

**Comment by ninoabbate** [comment]
Hey @yahavb thanks for opening this issue, sorry for the late reply, feel free to fork the repo and add your changes.
